#ifndef __COMMONDEFINE__H__
#define __COMMONDEFINE__H__

#define CONVERT_CMD_OPTION_ENCRPT_TOFILE		L"-enc"
#define CONVERT_CMD_OPTION_DECRPT_FROMFILE		L"-dec"
#define CONVERT_CMD_OPTION_ENCRPT_TOZIP		L"-ezip"
#define CONVERT_CMD_OPTION_DECRPT_FROMZIP		L"-dzip"

#define CONVERT_CMD_ENCRPTTYPE_RC4		L"rc4"

#define CONVERT_CMD_SHOWPROCDIALOG		L"1"
#define CONVERT_CMD_NOTSHOWPROCDIALOG	L"0"

#define CONVERT_OPTIONCODE_ENCRPT_TOFILE	0
#define CONVERT_OPTIONCODE_DECRPT_FROMFILE	1
#define CONVERT_OPTIONCODE_ENCRPT_TOZIP		3
#define CONVERT_OPTIONCODE_DECRPT_FROMZIP	4


#endif